In [1]:
import pandas as pd

In [14]:
df=pd.read_csv('train.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:
df=df.dropna()

In [4]:
df.head(55)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   
12  12  Russian Researchers Discover Secret Nazi Milit...   
13  13  US Officials See No Link Between Trump and Russia   
14  14  Re: Yes, There Are Paid Government Trolls On S...   
15  15  In Major League Soccer, Argentines Find a Home...   
16  16  Wells Fargo Chief Abruptly Steps Down - The Ne...   
17  17  Anonymous Donor Pays $2.5 Million To Release E...   
18  18                          FBI Closes In On Hillary!   
19  19  Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...   
21  21  Monica Lewinsky, Clinton Sex Scandal Set for ’...   
22  22  Rob Reiner: Trump Is ’Mentally Unstable’ - Bre...   
24  24  Abortion Pill Orders Rise in 7 Latin American ...   
25  25  Nukes and the UN: a Historic Treaty to Ban Nuc...   
26  26  EXCLUSIVE: Islamic State Supporters Vow to ‘Sh...   
27  27  Humiliated Hillary Tries To Hide What Camera C...   
28  28  Andrea Tantaros of Fox News Claims Retaliation...   
29  29  How Hillary Clinton Became a Hawk - The New Yo...   
30  30  Chuck Todd to BuzzFeed EIC: ’You Just Publishe...   
32  32  Having Won, Boris Johnson and ‘Brexit’ Leaders...   
33  33  Texas Oil Fields Rebound From Price Lull, but ...   
34  34  Bayer Deal for Monsanto Follows Agribusiness T...   
35  35  Russia Moves to Ban Jehovah’s Witnesses as ‘Ex...   
36  36  Re: Why We Are Still In ‘The Danger Zone’ Unti...   
37  37            Open Thread (NOT U.S. Election) 2016-39   
38  38  Democrat Gutierrez Blames Chicago’s Gun Violen...   
39  39  Avoiding Peanuts to Avoid an Allergy Is a Bad ...   
40  40  MRI Shows Detailed Images of 20-Week Unborn Ba...   
41  41      4 of the Best Kinds of Milk That Aren’t Dairy   
42  42  Ryan Lochte Dropped by Speedo USA and Other Re...   
44  44  Conservatives Urge Sessions to Clean Out Obama...   
45  45  Internal Inquiry Sealed the Fate of Roger Aile...   
46  46  Press TV Debate: Duff on Lebanon, Hezbollah an...   
48  48  Samsung, After Combustible Galaxy Note 7, Unve...   
49  49  Poland Vows Referendum on Migrant Quota Amidst...   
50  50                       Sparking An Inner Revolution   
52  52  Study: More Than Half of Car Crashes Involve D...   
55  55  The Trump Election Will Spark More Individual ...   
56  56  Ep. 544 FADE to BLACK Jimmy Church w/ Laura Ei...   
57  57           Cognition and True Islam - A Book Review   
58  58  If Donald Trump Wins The Election, It Will Be ...   
59  59  Mindful Eating as Way to Fight Bingeing - The ...   
60  60  The Major Potential Impact of a Corporate Tax ...   
61  61  I wonder what GLP will be like the day after t...   
62  62  3 Makers of World’s Smallest Machines Awarded ...   
63  63  Massive Anti-Trump Protests, Union Square NYC ...   
64  64  Review: ‘Lion’ Brings Tears for a Lost Boy, Wi...   

                                               author  \
0                                       Darrell Lucus   
1                                     Daniel J. Flynn   
2                                  Consortiumnews.com   
3                                     Jessica Purkiss   
4                                      Howard Portnoy   
5                                     Daniel Nussbaum   
7                                     Alissa J. Rubin   
9                        Megan Twohey and Scott Shane   
10                                        Aaron Klein   
11               

In [5]:
X=df.drop('label',axis=1)

In [6]:
y=df['label']

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [8]:
voc_size=5000

In [9]:
message=X.copy()
message.reset_index(inplace=True)

In [10]:
import nltk
import re
from nltk.corpus import stopwords

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [13]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 

In [17]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4437 1486 1428]
 [   0    0    0 ... 2480  771 4039]
 [   0    0    0 ... 2679   50 4123]
 ...
 [   0    0    0 ... 2990 3024 3176]
 [   0    0    0 ... 1993 3340 4667]
 [   0    0    0 ... 3216 4680  421]]


In [18]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 13s 34ms/step - loss: 0.3299 - accuracy: 0.8442 - val_loss: 0.2008 - val_accuracy: 0.9122
Epoch 2/10
192/192 [==============================] - 6s 29ms/step - loss: 0.1326 - accuracy: 0.9491 - val_loss: 0.1989 - val_accuracy: 0.9148
Epoch 3/10
192/192 [==============================] - 6s 31ms/step - loss: 0.0960 - accuracy: 0.9662 - val_loss: 0.2166 - val_accuracy: 0.9080
Epoch 4/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0677 - accuracy: 0.9773 - val_loss: 0.2823 - val_accuracy: 0.9112
Epoch 5/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0489 - accuracy: 0.9841 - val_loss: 0.2647 - val_accuracy: 0.9075
Epoch 6/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0343 - accuracy: 0.9888 - val_loss: 0.3412 - val_accuracy: 0.9067
Epoch 7/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0221 - accuracy: 0.9931 - val_loss: 0.4441 - val_accuracy: 0.906

In [24]:
y_pred=model.predict_classes(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

c:\users\dell\firstproject\natural_language_processing\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[3103,  316],
       [ 259, 2357]], dtype=int64)